# Generated by Django 5.1.5 on 2025-01-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('poster', models.URLField()),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
    ]
